version: '2'
services:
    # nginx:
    #     build: ./Nginx
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     volumes:
    #         - ./Nginx/www:/usr/share/nginx/html
    #         - ./Nginx/logs:/var/log/nginx
    #         - ./Nginx/conf/conf.d:/etc/nginx/conf.d
    #         - ./Nginx/ssl:/etc/nginx/ssl
    #     networks:
    #         - code-network
    #     depends_on:
    #         - phpfpm

    # phpfpm:
    #     build: ./Php-fpm
    #     ports:
    #         - "9000:9000"
    #     links:
    #         - mariadb:db
    #         - redis:redis
    #     volumes:
    #         - ./Nginx/www:/usr/share/nginx/html
    #         - ./Php-fpm/conf/supervisor.d:/etc/supervisor/conf.d
    #         - ./Php-fpm/conf/cron.d:/etc/cron.d
    #     networks:
    #         - code-network

    # rails:
    #     build: ./Rails
    #     command: /bin/sh -c "rm -f tmp/pids/server.pid &&  bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - ./Nginx/www/www.duxiaodou.com:/myapp
    #     networks:
    #         - code-network


    # mariadb:
    #     build: ./MariaDB
    #     restart: always
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./MariaDb/data:/var/lib/mysql
    #         - ./MariaDb/conf/conf.d:/etc/mysql/conf.d
    #     environment:
    #         MYSQL_USER: root
    #         MYSQL_ROOT_PASSWORD: root
    #     networks:
    #         - code-network

    # redis:
    #     build: ./Redis
    #     restart: always
    #     ports:
    #         - "6379:6379"
    #     volumes:
    #         - ./Redis/data:/data
    #     environment:
    #         REDIS_PASSWORD: redis
    #     networks:
    #         - code-network

    # rabbitmq:
    #     build: ./RabbitMQ
    #     restart: always
    #     ports:
    #         - "5672:5672"
    #         - "15672:15672"
    #     environment:
    #         RABBITMQ_DEFAULT_USER: rabbitmq
    #         RABBITMQ_DEFAULT_PASS: password
    #     networks:
    #         - code-network

    # supervisor:
    #     build: ./Supervisor
    #     volumes:
    #         - ./Supervisor/conf.d:/etc/supervisor/conf.d
    #         - ./Nginx/www:/usr/share/nginx/html
    #     depends_on:
    #         - phpfpm
    #     networks:
    #         - code-network

    # cron:
    #     build: ./Cron
    #     depends_on:
    #         - phpfpm
    #     volumes:
    #         - ./Cron/cron.d:/etc/cron.d
    #         - ./Nginx/www:/usr/share/nginx/html
    #         - ./Cron/logs:/var/log/cron
    #     networks:
    #         - code-network

    # jenkins:
    #     build: ./Jenkins
    #     ports:
    #         - "8080:8080"
    #         - "50000:50000"
    #     volumes:
    #         - ./Nginx/www:/var/jenkins_home/workshop
    #         - ./Jenkins/data:/var/jenkins_home
    #     networks:
    #         - code-network

    # gitlab-runner:
    #     build: ./Gitlab-runner
    #     volumes:
    #          - ./Nginx/www:/usr/share/nginx/html
    #          - ./Gitlab-runner/config/config.toml:/etc/gitlab-runner/config.toml
    #          - /var/run/docker.sock:/var/run/docker.sock
    #     networks:
    #          - code-network

networks:
    code-network:
        driver: bridge